MasterDetails/Models/Unit.cs
namespace MasterDetails.Models;

public class Unit
{
    public int Id { get; set; }
    public string UnitName { get; set; }
    public virtual List<PurchaseProduct> PurchaseProducts { get; set; } = new List<PurchaseProduct>();

}

MasterDetails/Controllers/UnitController.cs
using MasterDetails.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MasterDetails.Controllers;

public class UnitController : Controller
{
    private readonly MasterDetailsDbContext _context;

    public UnitController(MasterDetailsDbContext context)
    {
        _context = context;
    }

    // GET: Unit
    public async Task<IActionResult> Index()
    {
        return View(await _context.Units.ToListAsync());
    }

    // GET: Unit/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Units == null)
        {
            return NotFound();
        }

        var unit = await _context.Units
            .FirstOrDefaultAsync(m => m.Id == id);
        if (unit == null)
        {
            return NotFound();
        }

        return View(unit);
    }

    // GET: Unit/Create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,UnitName")] Unit unit)
    {
        if (ModelState.IsValid)
        {
            _context.Add(unit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(unit);
    }

    // GET: unit/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Units == null)
        {
            return NotFound();
        }

        var unit = await _context.Units.FindAsync(id);
        if (unit == null)
        {
            return NotFound();
        }
        return View(unit);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,UnitName")] Unit unit)
    {
        if (id != unit.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(unit);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UnitExists(unit.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(unit);
    }

    // GET: Unit/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Units == null)
        {
            return NotFound();
        }

        var unit = await _context.Units
            .FirstOrDefaultAsync(m => m.Id == id);
        if (unit == null)
        {
            return NotFound();
        }

        return View(unit);
    }

    // POST: Unit/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Units == null)
        {
            return Problem("Entity set 'AppDbContext.Units'  is null.");
        }
        var unit = await _context.Units.FindAsync(id);
        if (unit != null)
        {
            _context.Units.Remove(unit);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool UnitExists(int id)
    {
        return _context.Units.Any(e => e.Id == id);
    }
}

MasterDetails/Views/Unit/Create.cshtml
@model MasterDetails.Models.Unit


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Unit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Unit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UnitName" class="control-label"></label>
                <input asp-for="UnitName" class="form-control" />
                <span asp-validation-for="UnitName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MasterDetails/Views/Unit/Delete.cshtml
@model MasterDetails.Models.Unit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Unit</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UnitName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UnitName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MasterDetails/Views/Unit/Details.cshtml
@model MasterDetails.Models.Unit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Unit</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UnitName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UnitName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MasterDetails/Views/Unit/Edit.cshtml
@model MasterDetails.Models.Unit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Unit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Unit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UnitName" class="control-label"></label>
                <input asp-for="UnitName" class="form-control" />
                <span asp-validation-for="UnitName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MasterDetails/Views/Unit/Index.cshtml
@model IEnumerable<MasterDetails.Models.Unit>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UnitName)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitName)
                </td>
             
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>